### ISSUE TITLE
Services support

### ISSUE THREAD

**Issue by alexgiano** [transitiverobotics/transitive#38]
Hello, I would like to inquire if the Transient Robotics platform supports sending and receiving ROS services. Currently, I am developing a web interface that requires some services to control certain actions on the robot, and I would like to evaluate your solution for a series of additional features that you offer. I have read that managing services may be a limitation of the MQTT communication protocol. I'm not sure if this is the right place to ask this question; if it isn't, I can move it to where it's more appropriate. Thank you very much.

**Comment by chfritz** [comment]
We don't currently have an existing capability to do this, but it has been requested by others, too, so we'll probably create one soon. Since you are asking this question here, on the github repo of the open-source Transitive framework, I'll also point out that you could write that capability yourself, if that's what you want. To get started with that, you'd follow these steps and then look at the starter code that is generated from it: https://transitiverobotics.com/docs/develop/creating_capabilities

To implement the service calls, I would use `mqttSync.mqtt` directly, i.e., not use mqttSync (which is for synchronizing stateful data), but the mqtt client itself. You can follow this example from the robot-agent itself, used to trigger agent actions, in this case restarting the agent, from the web:

https://github.com/transitiverobotics/transitive/blob/bf7aadaef4c6508b5195ee9f33079ac4e18370f6/cloud/app/web_components/robot-agent-device.jsx#L294-L298

MQTT does not have any built-in support for RPCs, so you'll need to think about the return value yourself. In the agent we do this by writing it into the synchronized data, where the web client will receive it, e.g., for receiving the package log upon request. This pattern is not ideal though and still needs some improvement.

But again, if this is more involved than you'd like, then you can also wait until we create a capability for it that you could then just install on your robots.

**Comment by alexgiano** [comment]
Thanks for your kind reply. I took a look at the solution proposed by you by searching for additional material online like [async-mqtt](https://github.com/mqttjs/async-mqtt) or [mqtt-json-rpc](https://github.com/rse/mqtt-json-rpc) but, given my limited knowledge of the mqtt protocol, i would most likely not be able to obtain a good result. Currently I will therefore remain on the websocket protocol but keeping an eye on the developments and implementations of your platform. Thanks so much again

**Comment by chfritz** [comment]
Makes sense. Just to clarify though: MQTTSync is not async-mqtt. The former is a protocol we've developed an it's documented [here](https://transitiverobotics.com/docs/learn/data_model) and [here](https://transitiverobotics.com/docs/sdk/common#mqttsync).
